### ISSUE TITLE
Loader resolving issue

### ISSUE THREAD

**Issue by woowe** [koute/parcel-plugin-cargo-web#4]
I am trying to build the example but I am running into some errors

running `parcel index.html` gives me this:

```
🚨  /<REDACTED>/example/example-crate/Cargo.toml: Cannot resolve dependency '/<REDACTED>/example/.cache/.cargo-web/loader-225fd694858c22a1024cc19dc9443f14.js' at '/<REDACTED>/example/.cache/.cargo-web/loader-225fd694858c22a1024cc19dc9443f14.js'
    at Resolver.resolve (/<REDACTED>/.nvm/versions/node/v9.8.0/lib/node_modules/parcel-bundler/src/Resolver.js:76:17)
    at <anonymous>
```

Node version: 9.8.0
Npm version: 5.6.0
Rustc version: 1.27.0-nightly
Cargo-web version: 0.6.10
Parcel version: 1.7.0
Parcel-plugin-cargo-web version: 0.1.0

**Comment by bgourlie** [comment]
I believe the fix for this is in the master branch, but not published to NPM yet. Change the parcel-plugin-cargo-web dependency in your package.json to a github dependency and it should work.

**Comment by woowe** [comment]
Hey there, sorry for the delay, I have downloaded the repo on a completely new computer and still the same issue.

Steps taken:
`npm i`
`npm run example`

Error produced:
```
🚨  /<REDACTED>/parcel-plugin-cargo-web/example/example-crate/Cargo.toml: Cannot resolve dependency '/<REDACTED>/parcel-plugin-cargo-web/.cache/.cargo-web/loader-ad5b967d73891b35ae7d60158a86a470.js' at '/<REDACTED>/parcel-plugin-cargo-web/.cache/.cargo-web/loader-ad5b967d73891b35ae7d60158a8    at Resolver.resolve (/<REDACTED>/parcel-plugin-cargo-web/node_modules/parcel-bundler/src/Resolver.js:76:17)
    at <anonymous>
```

Versions:
Node: 9.4.0
Npm: 5.6.0
Rustc: 1.27.0-nightly
Cargo-web: 0.6.10
Parcel: 1.7.0

**Comment by bgourlie** [comment]
Can you post the line where you specify the parce plugin dependency in your
package.json?

**Comment by woowe** [comment]
Absolutely, it is just the example in the repo:

```
"dependencies": {
    "parcel-bundler": "^1.5.1"
  },
"devDependencies": {
    "parcel-plugin-cargo-web": "file:.."
  }
```

**Comment by koute** [comment]
Yep. Looks like it's broken with Parcel `1.7`, and to me it looks like it's a bug in Parcel. Looks like `Asset::addDependency` broke (well, whatever code which uses what we put in `addDependency` broke...) and stopped accepting absolute paths.

Fixed and `0.2.0` published. (Well, *hopefully* it works.... I didn't test it out too thoroughly.)

**Comment by woowe** [comment]
I just re-downloaded this repo, ran the example and everything work! Wow, amazing job! Now I can test out parcel and rust -> wasm at the same time :smile: .

**Comment by koute** [comment]
Great to hear that!

And thanks for the report!
