### ISSUE TITLE
The "path" argument must be of type string

### ISSUE THREAD

**Issue by vladbat00** [koute/parcel-plugin-cargo-web#5]
Greetings!

I try to compile your example and it fails with the following error:
```
mvlabat@Vladislavs-MacBook-Pro ~/js/parcel-plugin-cargo-web/example $ parcel index.html
Server running at http://localhost:1234
🚨  The "path" argument must be of type string
    at assertPath (path.js:39:11)
    at Object.isAbsolute (path.js:1147:5)
    at Resolver.resolve (/Users/mvlabat/.config/yarn/global/node_modules/parcel-bundler/src/Resolver.js:67:14)
    at <anonymous>
```

```
mvlabat@Vladislavs-MacBook-Pro ~/js/parcel-plugin-cargo-web/example $ node -v
v9.11.1
mvlabat@Vladislavs-MacBook-Pro ~/js/parcel-plugin-cargo-web/example $ parcel -V
1.7.1
```

**Comment by vladbat00** [comment]
Just tested with parcel 1.7.0 - everything works. Seems like some latest changes broke things

**Comment by koute** [comment]
Thanks for the report. Yes, 1.7.1 broke our plugin. Until I'll fix it you can keep on using 1.7.0.

**Comment by Victor-Savu** [comment]
@koute any hints as to how one could debug this? Would you accept contributions for fixing this issue?

**Comment by koute** [comment]
@Victor-Savu Of course I would!

As to how should this be debugged - well, that's a little harder. What I did the last time Parcel broke my plugin was that I went to where the exception is thrown, started adding a bunch of `console.log`s and fiddled with the code to figure out why it's thrown or how I could work around it.

**Comment by Victor-Savu** [comment]
You read my mind :) Let's see where this goes. It's annoying that the stack trace is so small and uninformative.

**Comment by Victor-Savu** [comment]
Seems like this is way out of my league :( Just wanted to say, please don't let my intrusion prevent anyone from solving this since they might have a much better chance than I do. I'll be celebrating when this is fixed, though :)
