### ISSUE TITLE
Cannot read property 'cacheDir' of undefined

### ISSUE THREAD

**Issue by phiresky** [koute/parcel-plugin-cargo-web#6]
This seems to be caused by https://github.com/parcel-bundler/parcel/commit/2f7be14aa9eea3fa9e8ee61591c001937d9757a1
which changes the api so the third argument becomes the second argument.

**Comment by koute** [comment]
Released as `0.3.0` on NPM!

**Comment by phiresky** [comment]
Thank you! This is what I was trying to do btw: https://github.com/phiresky/rust-brotli-wasm (since all existing js encoders for brotli are broken or badly packaged)
